version: "3.3"
services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - "./web/src:/web/src"
      - "./web/public:/web/public"
    ports:
      - "3000:3000"
    stdin_open: true

  db:
    container_name: db
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    environment:
      POSTGRES_USER: nimble
      POSTGRES_PASSWORD: nimble-test
      POSTGRES_DB: nimble
    ports:
      - "5432:5432"